config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'home#toggle_dark_mode' => 'home#toggle_dark_mode', as: :toggle_dark_mode
  post 'push_notification_address' => 'home#create_push_notification_address'

  resources :registration, only: [:new, :create]
  get 'registration/link'
  post 'registration/submit_phone' => 'registration/submit_phone', as: :submit_phone
  get 'registration/set_password'
  post 'registration/complete_account' => 'registration/complete_account', as: :complete_account

  post 'login/' => 'login#login'
  delete 'logout/' => 'login#logout'

  get 'request/new' => 'booking_requests#new', as: :new_request
  post 'request' => 'booking_requests#create', as: :create_request
  delete 'request/:id' => 'booking_requests#delete', as: :delete_request
  delete 'request/booking/:id' => 'booking_requests#delete_booking', as: :delete_booking
end

app/models/booking_request.rb
require 'net/https'

class BookingRequest
  def self.create(params, auth_token)
    uri = URI("#{ENV['MAIN_APP_URL']}/customer_app/request")
    response = Net::HTTP.post(uri, params.to_h.to_json, {
      'Content-Type' => 'application/json',
      'Authorization' => auth_token
    })
    if !response.code.starts_with?('4') && !response.code.starts_with?('5')
      response.body || 'Success'
    else
      Rails.logger.error("'Error in BookingRequest.create: with code #{response.code} - #{response.body}'")
      nil
    end
  end

  def self.get_booking_availability
    uri = URI("#{ENV['MAIN_APP_URL']}/customer_app/booking_availability.json")
    response = Net::HTTP.get_response(uri)
    if response.body.present?
      avl = JSON.parse response.body
      ['available', 'not_confirmed_as_available', 'unavailable', 'unconfirmed'].map do |key|
        avl[key].map { |d| d.to_date.strftime('%m/%d/%Y') }
      end
    else
      Rails.logger.error("'Error in BookingRequest.get_booking_availability: with code #{response.code} - #{response.body}'")
      'Failed to connect to server, please try again later'
    end
  end

  def self.delete(id, auth_token)
    uri = URI("#{ENV['MAIN_APP_URL']}/customer_app/request/#{id}")
    req = Net::HTTP.new(uri.host, uri.port)
    req.use_ssl = uri.scheme == 'https'
    response = req.delete(uri.path, 'Authorization' => auth_token)
    if !response.code.starts_with?('4') && !response.code.starts_with?('5')
      response.body || 'Success'
    else
      Rails.logger.error("'Error in BookingRequest.delete: with code #{response.code} - #{response.body}'")
      nil
    end
  end

  def self.delete_booking(id, auth_token)
    uri = URI("#{ENV['MAIN_APP_URL']}/customer_app/booking/#{id}")
    req = Net::HTTP.new(uri.host, uri.port)
    req.use_ssl = uri.scheme == 'https'
    response = req.delete(uri.path, 'Authorization' => auth_token)
    if !response.code.starts_with?('4') && !response.code.starts_with?('5')
      response.body || 'Success'
    else
      Rails.logger.error("'Error in BookingRequest.delete_booking: with code #{response.code} - #{response.body}'")
      nil
    end
  end
end

app/controllers/booking_requests_controller.rb
include ApplicationHelper

class BookingRequestsController < ApplicationController
  before_action :redirect_if_tokenless

  # GET /request/new
  def new
    @available, @not_confirmed_as_available,
      @unavailable, @unconfirmed = BookingRequest.get_booking_availability
  end

  # POST /request
  def create
    par = params.permit(:collection_dates, :delivery_dates, :additional_requirements)
    if par[:collection_dates].blank?
      redirect_to root_path, alert: 'Sorry, there has been an error parsing the dates, please try again.'
    end
    notice_msg = 'Request successfully sent.'
    if params['selected-uncertain'] != 'true' && params['additional_requirements'].blank?
      notice_msg = "Booked ironing on #{Date.strptime(par[:collection_dates], "%m/%d/%Y").to_fs}."
    end
    par[:collection_dates] = par[:collection_dates]&.split(',')
    par[:delivery_dates] = par[:delivery_dates]&.split(',')
    if BookingRequest.create(par, session[:auth_token]).nil?
      authentication_expired
    else
      redirect_to root_path, notice: notice_msg
    end
  end

  # DELETE /request/1
  def delete
    if BookingRequest.delete(params[:id], session[:auth_token]).nil?
      authentication_expired
    else
      redirect_to root_path, notice: 'Request cancelled.'
    end
  end

  # DELETE /request/booking/1
  def delete_booking
    if BookingRequest.delete_booking(params[:id], session[:auth_token]).nil?
      authentication_expired
    else
      redirect_to root_path, notice: 'Booking cancelled.'
    end
  end
end

app/views/booking_requests/_new_request_form.html.erb
<div class="form-group string" data-controller="request">
  <h2>Collection</h2>
  <div id="request_datepicker"></div>
  <span id="availability"
        data-available="<%= @available %>"
        data-not-confirmed-as-available="<%= @not_confirmed_as_available %>"
        data-unavailable="<%= @unavailable %>"
        data-unconfirmed="<%= @unconfirmed %>">
  </span>
  <input id="request_datepicker_input" type="hidden" name="collection_dates">
  <input id="request_datepicker_delivery_input" type="hidden" name="delivery_dates">
  <input id="selected-uncertain" type="hidden" name="selected-uncertain">
</div>
<div>
  <button id="more-dates-btn" class="btn btn-outline-success" type="button" data-bs-toggle="collapse"
          data-bs-target="#more-dates" aria-expanded="false" aria-controls="more-dates">
    Looking for a different date?
  </button>
</div>
<div class="form-group string">
  <div class="collapse" id="more-dates">
    <div class="card card-body">
      <u>Please select one or more of the following dates, and we will confirm your booking when we know whether we are available on one of them.</u>
      <div id="datepicker-uncertain-days"></div>
    </div>
  </div>
</div>
<hr />
<h2>Delivery</h2>
<div id="delivery-initial-text">Delivery is usually 2 days after collection.</div>
<div id="delivery-date-text" style="display: none">Delivery will be booked for <span id="delivery-date-label">?</span>.</div>
<div id="delivery-multiple-dates-text" style="display: none">Delivery requested for one of the dates you selected. We will contact you if we are not available on any of them.</div>
<div id="delivery-date-options" style="display: none">
  <button id="delivery-dates-btn" class="btn btn-outline-success" type="button" data-bs-toggle="collapse"
          data-bs-target="#delivery-dates" aria-expanded="false" aria-controls="delivery-dates">
    Looking for a different delivery date?
  </button>
  <div class="form-group string">
    <div class="collapse" id="delivery-dates">
      <div class="card card-body">
        <div id="datepicker-delivery-days"></div>
      </div>
    </div>
  </div>
</div>
<div id="more-delivery-dates-options" style="display: none">
  <button id="more-delivery-dates-btn" class="btn btn-outline-success" type="button" data-bs-toggle="collapse"
          data-bs-target="#more-delivery-dates" aria-expanded="false" aria-controls="more-delivery-dates">
    More delivery dates (we might not be available on those)
  </button>
  <div class="form-group string">
    <div class="collapse" id="more-delivery-dates">
      <u>Please select one or more of the following dates, and we will confirm your delivery when we know whether we are available on one of them.</u>
      <div class="card card-body">
        <div id="datepicker-more-delivery-days"></div>
      </div>
    </div>
  </div>
</div>
<br />
<div class="form-group string">
  <%= form.label :additional_requirements, 'Additional requirements', class: "control-label string" %>
  <%= form.text_area :additional_requirements, class: "form-control string" %>
  <p id="additional-requirements-info">If you have additional requirements, then the requested booking will need to be confirmed by us.</p>
</div>

app/views/booking_requests/new.html.erb
<%= link_to 'Back', root_path, class: 'btn btn-outline-primary btn-lg', role: 'button' %>
<h2>Make a booking</h2>

<hr />

<%= form_with url: create_request_path do |form| %>
  <%= render partial: 'new_request_form', locals: { form: form } %>
  <%= form.submit "Submit", id: 'submit-request', class: "btn btn-primary", disabled: true %>
<% end %>