config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'home#toggle_dark_mode' => 'home#toggle_dark_mode', as: :toggle_dark_mode
  post 'push_notification_address' => 'home#create_push_notification_address'

  resources :registration, only: [:new, :create]
  get 'registration/link'
  post 'registration/submit_phone' => 'registration/submit_phone', as: :submit_phone
  get 'registration/set_password'
  post 'registration/complete_account' => 'registration/complete_account', as: :complete_account

  post 'login/' => 'login#login'
  delete 'logout/' => 'login#logout'

  get 'request/new' => 'booking_requests#new', as: :new_request
  post 'request' => 'booking_requests#create', as: :create_request
  delete 'request/:id' => 'booking_requests#delete', as: :delete_request
  delete 'request/booking/:id' => 'booking_requests#delete_booking', as: :delete_booking
end

app/controllers/home_controller.rb
include ApplicationHelper

class HomeController < ApplicationController

  # GET /
  def index
    if session[:auth_token].present?
      res = BookingInfoFetcher.fetch(session[:auth_token])
      if res.nil?
        authentication_expired
      else
        @booking_info = res
      end
    else
      render 'unauthenticated'
    end
  end

  # POST /push_notification_address
  def create_push_notification_address
    CustomerRegistrator.register_push_notification(push_notification_address_params.to_h, session[:auth_token])
  end

  # POST /toggle_dark_mode
  def toggle_dark_mode
    par = params.permit(:darkMode)[:darkMode]
    p par
    p params
    if par == 'on'
      cookies[:dark_mode] = 'on'
    else
      cookies.delete(:dark_mode)
    end
    redirect_to root_path
  end

  private

  def push_notification_address_params
    params.permit(:endpoint, :auth_key, :p256dh_key)
  end
end

app/views/home/_data_field.html.erb
<% if data[key].present? %>
  <% displayed_key = key.capitalize.gsub('_', ' ') if local_assigns[:displayed_key].nil? %>
  <tr>
    <th class="w-25"><%= displayed_key %></th>
    <td><%= data[key] %></td>
  </tr>
<% end -%>

app/views/home/index.html.erb
<div class="center">
  <%= link_to 'Request ironing', new_request_path, class: 'btn btn-outline-primary btn-lg', role: 'button' %>
  <%= button_to 'Log out', logout_path, class: 'btn btn-primary btn-lg active', role: 'button',
                method: :delete, form: { class: 'd-inline' } %>
  <div class="form-check form-switch" style="float: right;">
    <%= form_with url: toggle_dark_mode_path, id: 'dark-mode-form' do |_| %>
      <input class="form-check-input" type="checkbox" role="switch" id="darkModeSwitch" name="darkMode" <%= cookies[:dark_mode] ? 'checked=checked' : nil %> style="transform: scale(1.6);">
      <label class="form-check-label" for="darkModeSwitch">&nbspDark mode</label>
    <% end %>
  </div>
</div>

<% if @booking_info['requests'].present? %>
  <h2>Pending requests</h2>
  <% @booking_info['requests'].each do |request| %>
    <table class="table table-striped">
      <tbody>
        <tr>
          <th class="w-25">Dates</th>
          <td><%= request['dates'].join(" | ") %></td>
        </tr>
        <% if request['delivery_dates'].present? %>
          <tr>
            <th class="w-25">Delivery dates</th>
            <td><%= request['delivery_dates'].join(" | ") %></td>
          </tr>
        <% end %>
        <tr>
          <th class="w-25">Date created</th>
          <td><%= request['created_at'] %></td>
        </tr>
        <% for key in %w[address additional_requirements] do %>
          <%= render partial: 'data_field', locals: {
            data: request, key: key
          } %>
        <% end -%>
        <tr>
          <th><%= link_to delete_request_path(request['id']), method: :delete,
                          data: { confirm: 'Are you sure?' },
                          class: 'btn btn-outline-danger', role: 'button' do %>
              Cancel
            <% end %>
          </th>
          <td></td>
        </tr>
      </tbody>
    </table>
    <hr />
  <% end %>
<% end -%>

<% if @booking_info['bookings'].present? %>
  <h2 data-controller="home">Active bookings</h2>
  <% @booking_info['bookings'].each_with_index do |booking, idx| %>
    <table class="table table-striped">
      <tbody>
        <% for key in %w[state collection_date delivery_date address] do %>
          <%= render partial: 'data_field', locals: {
            data: booking, key: key
          } %>
        <% end -%>
        <% if booking['delivery_date'].blank? && booking['delivery_dates'].present? %>
          <tr>
            <th class="w-25">Requested delivery dates</th>
            <td><%= booking['delivery_dates'].join(" | ") %></td>
          </tr>
        <% end %>
        <% if booking['visit_time'].present? %>
          <%= render partial: 'data_field', locals: {
            data: booking, key: 'visit_time', displayed_key: 'Visit time (approximate)'
          } %>
        <% else %>
          <tr>
            <th class="w-25">Visit time</th>
            <td>To be announced at <%= booking['sched_deadline'] %></td>
          </tr>
          <%= render partial: 'data_field', locals: {
            data: booking, key: 'visit_constraints', displayed_key: 'Visit times'
          } %>
        <% end -%>
        <% if booking['state'] == 'Ironed' %>
          <tr>
            <th class="w-25">Cost</th>
            <td><%= booking['total_cost'] %></td>
          </tr>
        <% end -%>
        <% if booking['state'] == 'Booked' && booking['visit_time'].blank? %>
          <tr>
            <th><%= link_to delete_booking_path(booking['id']), method: :delete,
                            data: { confirm: 'Are you sure?' },
                            class: 'btn btn-outline-danger', role: 'button' do %>
                Cancel
              <% end %>
            </th>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% if booking['state'] == 'Ironed' %>
      <button id="btn-cost-breakdown-<%= idx %>" class="btn btn-outline-success" type="button" data-bs-toggle="collapse"
              data-bs-target="#cost-breakdown-<%= idx %>" aria-expanded="false" aria-controls="cost-breakdown-<%= idx %>">
        Show breakdown
      </button>
    <% end -%>
    <% if booking['state'] == 'Ironed' %>
      <div class="collapse" id="cost-breakdown-<%= idx %>">
        <div class="card card-body">
          <% booking['cost_breakdown'].each do |item| %>
            <table class="table table-bordered border-secondary">
              <tbody>
                <% for key in %w[name cost_per_item cost_per_hour hours count discount total_cost] do %>
                  <%= render partial: 'data_field', locals: {
                    data: item, key: key
                  } %>
                <% end -%>
              </tbody>
            </table>
          <% end -%>
        </div>
      </div>
    <% end %>
    <hr />
  <% end %>
<% end -%>

<% if @booking_info['requests'].blank? && @booking_info['bookings'].blank? %>
  <h3>No active requests or bookings.</h3>
<% end -%>

<div id="notifications-div" class="border border-success" hidden>
  <h4>Please sign up for browser notifications. We will only notify you one of the following reasons: <button class="btn btn-outline-secondary" id="hide-notifications-btn">&times</button></h4>
  <div>
    1. You have requested a date for collection or delivery, and it was approved.<br />
    2. We just confirmed the exact time for visiting you today.<br />
    3. The driver is 5 minutes away from you.<br />
  </div>
  <button class="btn btn-success btn-lg" id="notifications-btn">Sign up for notifications</button>
  <button class="btn btn-secondary btn-lg" id="dismiss-notifications-btn">Dismiss</button>
</div>

<span id="has-notification-address" data-value="<%= @booking_info['has_notification_address'] %>"></span>
<span id="geocodes"
      data-present="<%= @booking_info['driver_geocode'].present? %>"
      data-customer="<%= @booking_info['geocode'] %>"
      data-driver="<%= @booking_info['driver_geocode'] %>"></span>
<% if @booking_info['driver_geocode'].present? %>
  <div id="map-canvas"></div>
<% end -%>

app/views/home/unauthenticated.html.erb
<div class="center">
  <p>Welcome to Cheap ironing services. New customers:</p>
  <%= link_to 'Register', new_registration_path, class: 'btn btn-outline-primary btn-lg', role: 'button' %>
  <hr />
  <p>Existing customers:</p>
  <%= link_to 'Link account', registration_link_path, class: 'btn btn-outline-primary btn-lg', role: 'button' %>
  <hr />
  <%= form_with url: login_path do |form| %>
    <div class="form-group string">
      <%= form.label :phone, class: "control-label string" do %>
        <abbr title="required">*</abbr>
        Mobile number
      <% end %>
      <%= form.text_field :phone, class: "form-control string input_width", required: true %>
    </div>
    <div class="form-group string">
      <%= form.label :password, class: "control-label string" do %>
        <abbr title="required">*</abbr>
        Password
      <% end %>
      <%= form.password_field :password, class: "form-control string input_width", required: true %>
    </div>
    <%= form.submit "Log in", class: "btn btn-primary" %>
  <% end %>
  <hr />
  <%= link_to 'Forgotten password', registration_link_path, class: 'btn btn-outline-primary btn-sm', role: 'button' %>
</div>